title: "Mahesh Kumar Tippanu"
description: "My journey from Civil Engineering to IT and beyond"
baseurl: ""
url: "https://maheshkumartippanu.github.io"

author:
  name: "Mahesh Kumar Tippanu"
  avatar: "/Name it: assets/img/Mahesh.jpg"
  email: "maheshkumartippanu@gmail.com"
  phone: "+91-6303186275"
  LinkedIn: "https://www.linkedin.com/in/mahesh-kumar-tippanu-343237a5/"

theme: jekyll-theme-chirpy
